spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://diopsamba408:Keg01EKDjuOgk0LP@baobab-academy.llpcqcb.mongodb.net/baobab_academy?retryWrites=true&w=majority&appName=baobab-academy}
      auto-index-creation: true
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:baobabAcademySecretKeyForJWTTokenGenerationMustBe32CharactersLong2024}
    expiration: ${JWT_EXPIRATION:86400000}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,https://baobab-academy-api-production.up.railway.app/api}

file:
  upload-dir: ${FILE_UPLOAD_DIR:/tmp/uploads}

# Configuration Cloudinary
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dnbyf2jqg}
  api-key: ${CLOUDINARY_API_KEY:692874425739111}
  api-secret: ${CLOUDINARY_API_SECRET:4DLEIJt_ImEVWVjKXDO_7NDzuko}

# Documentation Swagger (désactivée en production)
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Logging optimisé pour production
logging:
  level:
    com.example.baobab_academy: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.data.mongodb: WARN
    org.mongodb.driver: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized